#!/usr/bin/perl -w
use lib qw(/usr/lib/arm-linux-gnueabihf/perl5/5.28);
use RRDs;
use strict;
use Getopt::Long;
my $rrd_files_dir ="/home/phidget/workspace/";
my %opts = ();
GetOptions(\%opts, 'debug!','h!','type=s','id=s','period=s');
my $file;
if ($opts{type} eq "temphum") {
	$file = $rrd_files_dir."temphumidity.rrd";
} elsif ($opts{type} eq "vpd") {
	$file = $rrd_files_dir."temphumidity.rrd";
} elsif ($opts{type} eq "grp") {
}
my $period = $opts{period};
my $end=RRDs::last($file);
my @args;
if ($period eq "day") {
@args=(
    "-",
    '-e', $end,
    '-v Past',
    '-w 520',
    '-h 160',
    '-l 0',
    '-u 3',
    '--slope-mode',
    '--title=VPD',
    '--watermark=Cary',
    '--right-axis-label=Future',
    '--color=ARROW#00FF00',
    '--color=BACK#000000',
    '--color=CANVAS#000000',
    '--color=SHADEA#00FF00',
    '--color=SHADEB#00FF00',
    '--color=GRID#00FF00',
    '--color=MGRID#00FF00',
    '--color=FONT#CC0033',
    '--color=AXIS#00FF00',
    "DEF:vpd=$file:vpd:AVERAGE",
    "DEF:vpdmax=$file:vpd:MAX",
    'AREA:vpd#0000ff:VPD kPa\u',     
    'HRULE:.45#EDC748:Target Min. VPD 0.45kPa(Wet)\r',
    'LINE1:vpdmax#ff00ff:Max. VPD kPa\u',    
    'HRULE:1.25#EC9D48:Target Max. VPD 1.25kPa(Dry)\r',
    'GPRINT:vpd:MIN:Min. VPD\: %2.3lfkPa\l',
    'GPRINT:vpd:MAX:Max. VPD\: %2.3lfkPa\l',
    'GPRINT:vpd:LAST:Current VPD\: %2.3lfKpa\l'
);
} else {
@args=(
    "-",
    '-e', $end,
    '-v Past',
    '-w 520',
    '-h 160',
    '-l 0',
    '-u 3',
    '--slope-mode',
    '--title=VPD',
    '--watermark=Cary',
    '--right-axis-label=Future',
    '--color=ARROW#00FF00',
    '--color=BACK#000000',
    '--color=CANVAS#000000',
    '--color=SHADEA#00FF00',
    '--color=SHADEB#00FF00',
    '--color=GRID#00FF00',
    '--color=MGRID#00FF00',
    '--color=FONT#CC0033',
    '--color=AXIS#00FF00',
    "DEF:vpd=$file:vpd:AVERAGE",
    "DEF:vpdmax=$file:vpd:MAX",
    'AREA:vpd#0000ff:VPD kPa\u',
    'HRULE:.45#EDC748:Target Min. VPD 0.45kPa(Wet)\r',
    'LINE1:vpd#ff00ff:Max. VPD kPa\u',
    'HRULE:1.25#EC9D48:Target Max. VPD 1.25kPa(Dry)\r',
    'GPRINT:vpd:MIN:Min. VPD\: %2.3lfkPa\l',
    'GPRINT:vpd:MAX:Max. VPD\: %2.3lfkPa\l',
    'GPRINT:vpd:AVERAGE:Avg. VPD\: %2.3lfkPa\l'
);
}
if ($period eq 'week') {
	push @args,('-s -1week');
} elsif ($period eq 'month') {
	push @args,('-s -1month');
} elsif ($period eq 'year') {
	push @args,('-s -1year');
} else {
	push @args,('-s -24h','-x','MINUTE:15:HOUR:1:HOUR:1:0:%H');
}
RRDs::graph(@args);
my $err=RRDs::error;
if ($err) {
	print "error: $err\n" if $err;
	exit(1);
}
exit(0);
